[build]
  # Diretório de publicação (raiz do projeto)
  publish = "."
  
  # Comandos de build (não necessário para este projeto)
  # command = ""

[build.environment]
  # Variáveis de ambiente para build
  NODE_VERSION = "18"

# Configurações de deploy
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

# Configurações de redirecionamento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; img-src 'self' data: https:; font-src 'self' https:;"

# Configurações de função (se necessário no futuro)
# [functions]
#   directory = "functions"
